### PR TITLE
Add a link to the GitHub diff

### LINKED ISSUE #90: Add a link to the github diff
See for example https://github.com/JuliaPackaging/Yggdrasil/pull/6095#issue-1537151181. I think these links are more useful than printing the title of commits (which are still useful for future reference in the git commit message), people can more easily see the actual code.

### PR DESCRIPTION
**Pull request by DilumAluthge**
Fixes #90

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
Here’s an example of what it looks like: https://github.com/bcbi-test/julia/pull/969

**Review by IanButterworth — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
