### PR TITLE
For some stdlibs, it is expected that the stdlib version number won't match the Julia version number

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Here's an example of a PR where `(Does not match)` is not the right thing: https://github.com/JuliaLang/julia/pull/51046

**Comment by IanButterworth** [comment]
I guess this will happen in upgradable stdlibs too? So maybe add DelimitedFiles?

**Comment by DilumAluthge** [comment]
> So maybe add DelimitedFiles?

Done!

**Comment by DilumAluthge** [comment]
@IanButterworth Can you give this another review?

**Review by IanButterworth — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
