### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@DilumAluthge Is this CI running at all?

**Comment by DilumAluthge** [comment]
We use Bors on this repo, so e.g. `bors try` or `bors merge`.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
