### PR TITLE
Fix version file parsing

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaLang/BumpStdlibs.jl/issues/61 ?

Untested

### CODE REVIEW

**Comment by IanButterworth** [comment]
Ok. It fails on nightly though, so the regex still needs work

**Comment by DilumAluthge** [comment]
No, the CI Julia version refers only to the Julia binary we run. The Julia source repo we use for CI (https://github.com/bcbi-test/julia) is the same for all CI jobs.

**Comment by DilumAluthge** [comment]
Instead of `@assert` (which may be disabled by default in the future), can you use conditionals?

**Comment by DilumAluthge** [comment]
I should probably document this better somewhere. Anyway, in production we have the upstream repository (https://github.com/JuliaLang/julia), but the bot user (DilumAluthgeBot) does not have commit permissions on the upstream, so it makes PRs from its fork (https://github.com/DilumAluthgeBot/julia).

In CI, we replicate this situation by having an "upstream" and a "fork" just for the purposes of CI.

The "CI upstream" (https://github.com/bcbi-test/julia) is not automatically kept in sync with the real upstream (https://github.com/JuliaLang/julia), but we should probably add a function at the beginning of the test suite that syncs the "CI upstream" with the "real upstream".

| Row | CI or production | Upstream or fork | Owner           | Repo                       |
| --- | ---------------- | ---------------- | --------------- | -------------------------- |
| 1   | Production       | Upstream         | JuliaLang       | [JuliaLang/julia][1]       |
| 2   | Production       | Fork             | DilumAluthgeBot | [DilumAluthgeBot/julia][2] |
| 3   | CI               | Upstream         | bcbi-test       | [bcbi-test/julia][3]       |
| 4   | CI               | Fork             | bcbi-test-user  | [bcbi-test-user/julia][4]  |

[1]: https://github.com/JuliaLang/julia
[2]: https://github.com/DilumAluthgeBot/julia
[3]: https://github.com/bcbi-test/julia
[4]: https://github.com/bcbi-test-user/julia

**Comment by DilumAluthge** [comment]
I was having some issues with CI on nightly. Can you comment out the "nightly" for now? We can uncomment in a separate PR.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Looks good - now let's make sure that all CI jobs pass.

**Pull request merged**
